stages:
  - test
  - upload

SpringTest:
  stage: test
  tags:
    - docker
  image: openjdk:13-jdk-alpine
  artifacts:
    expire_in: 1 week
    reports:
      junit: caustic/target/surefire-reports/*.xml
  cache:
    paths:
      - /root/.m2/
      - caustic/target/
  script:
    - cd caustic
    - sed 's/localhost/cs319-105.misc.iastate.edu/' -i src/main/resources/application.properties
    - sed 's/root/caustic/' -i src/main/resources/application.properties
    - ./mvnw test

# RunnerTest:
#   stage: test
#   tags:
#     - docker
#   image: ryan3r/caustic-runner
#   script:
#     - cp -r runner/runner /go/src
#     - cd /go/src/runner
#     - go test
#   only:
#     - master
#     - /-runner$/

DockerUpload:
  stage: upload
  when: manual
  tags:
    - shell
  script:
    - sudo upload-to-docker
  only:
    - master
