stages:
  - test

SpringTest:
  stage: test
  tags:
    - docker
  image: openjdk:13-jdk-alpine
  script:
    - cd caustic
    - sed 's/localhost/cs319-105.misc.iastate.edu/' -i src/main/resources/application.properties
    - sed 's/root/caustic/' -i src/main/resources/application.properties
    - ./mvnw test
