stages:
  - test
  - build
  - upload

SpringTest:
  stage: test
  tags:
    - docker
  image: openjdk:13-jdk-alpine
  cache:
    paths:
      - caustic/.m2/
      - caustic/target/
  script:
    - cd caustic
    - sed 's/localhost/cs319-105.misc.iastate.edu/' -i src/main/resources/application.properties
    - sed 's/root/caustic/' -i src/main/resources/application.properties
    - ./mvnw -B test -Dmaven.repo.local=.m2/repository

RunnerTest:
  stage: test
  tags:
    - docker
  image: golang
  before_script:
    - go get github.com/docker/docker/client
    - go get github.com/DATA-DOG/go-sqlmock
    - go get github.com/ahmetalpbalkan/dlog
    - go get github.com/go-sql-driver/mysql
  script:
    - cp -r runner /go/src
    - cd /go/src/runner
    - go test -cover

RunnerBuild:
  stage: build
  tags:
    - docker
  image: golang
  artifacts:
    expire_in: 1 week
    paths:
      - build/
  before_script:
    - go get github.com/docker/docker/client
    - go get github.com/DATA-DOG/go-sqlmock
    - go get github.com/ahmetalpbalkan/dlog
    - go get github.com/go-sql-driver/mysql
  script:
    - cp -r runner /go/src
    - pushd /go/src/runner
    - go build *.go
    - mv db caustic-linux
    - GOOS=darwin go build *.go
    - mv db caustic-macos
    - GOOS=windows go build *.go
    - mv db.exe caustic-windows.exe
    - popd
    - mkdir build
    - cp /go/src/runner/caustic-* build
    - cp /go/src/runner/caustic-* /www
  only:
    - master
    - tags

DockerUpload:
  stage: upload
  tags:
    - shell
  script:
    - sudo systemctl stop caustic
    - cp /var/www/html/caustic-linux /usr/caustic/runner
    - docker-compose build
    - cp docker-compose.prod.yml /usr/caustic/docker-compose.yml
    - cd /usr/caustic
    - docker-compose down
    - docker-compose up -d
    - sudo systemctl start caustic
  only:
    - tags
