stages:
  - test
  - upload

SpringTest:
  stage: test
  tags:
    - docker
  image: openjdk:13-jdk-alpine
  artifacts:
    expire_in: 1 week
    reports:
      junit: caustic/target/surefire-reports/*.xml
  script:
    - cd caustic
    - sed 's/localhost/cs319-105.misc.iastate.edu/' -i src/main/resources/application.properties
    - sed 's/root/caustic/' -i src/main/resources/application.properties
    - ./mvnw test
  except:
    - /-runner$/

RunnerTest:
  stage: test
  tags:
    - docker
  image: golang
  artifacts:
    expire_in: 1 week
    reports:
      junit: runner/report.xml
  before_script:
    - go get -u github.com/jstemmer/go-junit-report
  script:
    - cd runner
    - go test -v 2>&1 | tee >(go-junit-report > report.xml)
  only:
    - master
    - /-runner$/

DockerUpload:
  stage: upload
  tags:
    - shell
  script:
    - upload-to-docker
  only:
    - tags
