stages:
  - test
  - upload

SpringTest:
  stage: test
  tags:
    - docker
  image: openjdk:13-jdk-alpine
  artifacts:
    expire_in: 1 week
    reports:
      junit: caustic/target/surefire-reports/*.xml
  cache:
    paths:
      - caustic/.m2/
      - caustic/target/
  script:
    - cd caustic
    - sed 's/localhost/cs319-105.misc.iastate.edu/' -i src/main/resources/application.properties
    - sed 's/root/caustic/' -i src/main/resources/application.properties
    - ./mvnw -B test -Dmaven.repo.local=.m2/repository

RunnerTest:
  stage: test
  tags:
    - docker
  image: ryan3r/caustic-runner
  before_script:
    - apk add --no-cache git
    - go get github.com/golang/glog
    - go get github.com/DATA-DOG/go-sqlmock
    - go get -u github.com/jstemmer/go-junit-report
  script:
    - cp -r runner/runner /go/src
    - pushd /go/src/runner
    - go test -v 2>&1 | tee >(go-junit-report > report.xml)
    - popd
    - cp /go/src/runner/report.xml .
  artifacts:
    expire_in: 1 week
    reports:
      junit: report.xml

DockerUpload:
  stage: upload
  tags:
    - shell
  script:
    - sudo upload-to-docker $CI_COMMIT_TAG
  only:
    - tags
