stages:
  - test
  - upload

SpringTest:
  stage: test
  tags:
    - docker
  image: openjdk:13-jdk-alpine
  cache:
    paths:
      - caustic/.m2/
      - caustic/target/
  script:
    - cd caustic
    - sed 's/localhost/cs319-105.misc.iastate.edu/' -i src/main/resources/application.properties
    - sed 's/root/caustic/' -i src/main/resources/application.properties
    - ./mvnw -B test -Dmaven.repo.local=.m2/repository

RunnerTest:
  stage: test
  tags:
    - docker
  image: ryan3r/caustic-runner
  before_script:
    - apk add --no-cache git
    - go get github.com/golang/glog
    - go get github.com/DATA-DOG/go-sqlmock
  script:
    - cp -r runner/runner /go/src
    - pushd /go/src/runner
    - go test -cover

DockerUpload:
  stage: upload
  tags:
    - shell
  script:
    - sudo upload-to-docker $CI_COMMIT_TAG
  only:
    - tags
