stages:
  - test

SpringTest:
  stage: test
  variables:
    MYSQL_ROOT_PASSWORD: Pa$$word1
    MYSQL_DATABASE: caustic
  services: 
    - mysql
  tags:
    - docker
  image: openjdk:13-jdk-alpine
  script:
    - cd caustic
    - ./mvnw test
