version: '3'
services:
  caustic:
    build: ./caustic
    image: ryan3r/caustic
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - db
    volumes:
      - "submissions:/mnt/submissions"

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "caustic"
    env_file: .env
    volumes:
      - "db:/var/lib/mysql"

  runner:
    image: ryan3r/caustic-runner
    build: ./runner
    depends_on:
      - caustic
    volumes:
      - "submissions:/mnt/submissions"

volumes:
  db:
  submissions:

