version: '3'
services:
  caustic:
    build: ./caustic
    image: ryan3r/caustic
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - db
    volumes:
      - "./runner/test-files:/mnt/submissions"

  db:
    image: mysql
    labels:
      com.ryan3r.caustic.is-db: "yes"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "caustic"
    env_file: .env
    volumes:
      - "db:/var/lib/mysql"

volumes:
  db:
  submissions:
