version: '3'
services:
  caustic:
    image: ryan3r/caustic
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - db
    volumes:
      - "./submissions:/mnt/submissions"
      - "./problems:/mnt/problems"

volumes:
  submissions:
